name: Deploy Backend to EC2

on:
  push:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-deploy.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted  # Now using your EC2 runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json

      - name: Install backend dependencies
        run: |
          cd legalpocket/legalpocket/backend
          npm ci

      - name: Inject .env file from PROD_ENV
        run: |
          echo "${{ secrets.PROD_ENV }}" > legalpocket/backend/.env

      - name: Run backend tests (if any)
        run: |
          cd legalpocket/backend
          npm test --if-present

      - name: Install PM2
        run: npm install -g pm2

      - name: Restart backend service with PM2
        run: |
          cd legalpocket/backend
          pm2 restart legal-pocket-compass-api || pm2 start app.js --name legalpocket-api
          pm2 save

      - name: ✅ Done
        run: echo "Backend deployment completed successfully on self-hosted runner!"
