# name: Deploy All

# on:
#   push:
#     branches: [ main ]
#   workflow_dispatch:

# jobs:
#   deploy-frontend:
#     runs-on: ubuntu-latest
#     needs: []
    
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Setup Node.js
#       uses: actions/setup-node@v4
#       with:
#         node-version: '18'
#         cache: 'npm'

#     - name: Install dependencies
#       run: npm ci

#     - name: Build project
#       run: npm run build
#       env:
#         VITE_AWS_USER_POOL_ID: ${{ secrets.VITE_AWS_USER_POOL_ID }}
#         VITE_AWS_USER_POOL_CLIENT_ID: ${{ secrets.VITE_AWS_USER_POOL_CLIENT_ID }}
#         VITE_AWS_IDENTITY_POOL_ID: ${{ secrets.VITE_AWS_IDENTITY_POOL_ID }}
#         VITE_API_URL: ${{ secrets.VITE_API_URL }}

#     - name: Deploy to Vercel
#       uses: amondnet/vercel-action@v25
#       with:
#         vercel-token: ${{ secrets.VERCEL_TOKEN }}
#         vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
#         vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
#         vercel-args: '--prod'

#   deploy-backend:
#     runs-on: ubuntu-latest
#     needs: []
    
#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Deploy to EC2
#       uses: appleboy/ssh-action@v1.0.3
#       with:
#         host: ${{ secrets.EC2_HOST }}
#         username: ${{ secrets.EC2_USERNAME }}
#         key: ${{ secrets.EC2_SSH_KEY }}
#         port: ${{ secrets.EC2_PORT }}
#         script: |
#           cd /var/www/legal-pocket-compass
#           git pull origin main
#           cd backend
#           npm ci --production
#           pm2 restart legal-pocket-compass-api
#           pm2 save 